### ISSUE TITLE
Busyness indicator. High cpu usage by Atom.

### ISSUE THREAD

**Issue by xanfus** [JunoLab/Atom.jl#105]
Atom uses as much as 27% of A8-6410 by 2 it's processes to render busyness bar-shaped indicator at lower left corner of the application window and cog indicator at the end of input block. At least it's something immediately visible. I wouldn't mind switching both off as long as i may rely on system monitor. Is there anything i could tweak in packages' settings concearning the subject?

**Comment by pfitzseb** [comment]
Have a look at https://github.com/JunoLab/atom-julia-client/issues/370, would be great to get feedback if those tweaks work or not.

I'll close this in favour of https://github.com/JunoLab/atom-ink/issues/142.
