### ISSUE TITLE
More light weight flame graphs

### ISSUE THREAD

**Issue by andreasnoack** [JunoLab/Atom.jl#112]
I tried to use `@profiler` to analyze the compilation of `Gadfly.render` and the flame graph took a long time to show up. Furthermore, it was very slow to navigate. I tried the same thing with StatProfilerHTML and it was able to handle the graph more smoothly so I wondered if the flame graphs in Juno could be more efficient. (Btw. I'm not sure what belongs in this issue tracker and what belongs in Juno.jl)

**Comment by pfitzseb** [comment]
The idea was to open new issues at Juno.jl and have maintainers move them to the appropriate repo if necessary, so here we go: https://github.com/JunoLab/atom-ink/issues/160.
