### ISSUE TITLE
REPL Warnings

### ISSUE THREAD

**Issue by sdmcallister** [JunoLab/Atom.jl#113]
In windows 10, Julia 6.2 it seems to work fine.

My work pc runs on Windows 7 (older power shell) and I continuously see errors like:

`WARNING: Atom.jl: unrecognised message validatepath.`

`WARNING: Atom.jl: unrecognised message changemodule.`

It can still run the code I input and I can print to the REPL, but all the warnings just gets messy.

**Comment by pfitzseb** [comment]
Please update to the latest version of Atom.jl and Juno.jl via `Pkg.update()`.

**Comment by cortner** [comment]
that fixed it for me.
