### ISSUE TITLE
n\hat doesn't render correctly in a comment.

### ISSUE THREAD

**Issue by Aether59** [JunoLab/Atom.jl#116]
Hi,

Julia client 0.6.8 and Julia 0.6.2 on Ubuntu 16.04 LTS.

In commented text, n\hat does not render correctly. Specifically, the hat comes after the n instead of over it.  However, e\hat does render correctly.  See screenshot attached.

![image](https://user-images.githubusercontent.com/30016456/36944304-bd5ae2b4-1fa1-11e8-8e91-cbdb75f2bcd3.png)

Non-critical. Haven't done a lot more research on it than that, just wanted to share.

Thanks.

**Comment by pfitzseb** [comment]
This is a font issue -- it seems likely that the font you're using doesn't have an italics version of that composite glyph. Not sure if there are fonts that support this properly.

**Comment by Aether59** [comment]
Thanks!
