### ISSUE TITLE
WARNING: Atom.jl: unrecognised message changeprompt.

### ISSUE THREAD

**Issue by sjlite** [JunoLab/Atom.jl#118]
Starting the julia kernel gives the following warning:

WARNING: Atom.jl: unrecognised message changeprompt.

any ideas what might be causing this / how to fix? thank you!

**Comment by pfitzseb** [comment]
Try `Pkg.updating()`. This error happens when the Atom and Julia packages are out-of-sync.

**Comment by sjlite** [comment]
Pkg.update() didn't work, updating Atom to the most recent version did. Thanks!
