### ISSUE TITLE
Cursor jumps away when running selected text

### ISSUE THREAD

**Issue by gustafsson** [JunoLab/Atom.jl#119]
If I select a piece of text and hit Shift+Enter that piece of text is executed and I get the result displayed after that selection. This is all good. But the cursor doesn't stay at the end of the selection but instead jumps to the end of the block. It seems to me that it jumps to the same place it would jump if I hit Sift+Enter without selecting any text.

I don't think the cursor should jump when running selected text.

**Comment by pfitzseb** [comment]
Generally the best place to open new issues is [here](https://github.com/JunoLab/Juno.jl).
