### ISSUE TITLE
AtomHelper at over 100% CPU on osx

### ISSUE THREAD

**Issue by TsurHerman** [JunoLab/Atom.jl#121]
I have a fresh install of Atom and Juno and thats it.
Without Juno and ink etc everything is relatively cool, with it my laptop overheats

**Comment by pfitzseb** [comment]
Ouch. Can you try setting the `Boot Mode` to basic and restart Atom? Are you evaluating anything or is Atom (and Julia)  completly idle?

**Comment by TsurHerman** [comment]
My bad! it was probably due to the modified sysimg I used, it had around 20-30 packages baked into it including Atom and Juno ... accumulated over a quite a few sessions of sysimg building.
I guess this process is not without side effects.. :-) 
I reverted to a fresh sysimg , updated all packages .. now everything works fine.
 I'll track the sysimg building process to see where this comes from .. but thats on my side :-) your side is good. 
you can close this

**Comment by pfitzseb** [comment]
Alright, glad you figured it out! :)
