### ISSUE TITLE
Atom.edit(::Module) doesn't work on Julia 1.0

### ISSUE THREAD

**Issue by ssfrr** [JunoLab/Atom.jl#131]
From [here](https://github.com/JunoLab/Atom.jl/blob/18ab0b2dfe2cc48eeeaf5378c13b31950578a0ac/src/utils.jl#L1-L4), `Pkg.dir` doesn't exist any more, and also it uses `Pkg` without importing it.

From [here](https://github.com/JuliaLang/Pkg.jl/issues/417#issuecomment-409839713) it seems that the new incantation should be `pathof(pkg)`.

Additionally my preference would be to run `atom -a pkgdir` rather than `atom pkgdir` so it will open it in the current window, but others may disagree.

**Comment by pfitzseb** [comment]
Right, I kinda forgot about all the package related methods we had. Will look into fixing this.
