### ISSUE TITLE
Atom.jl spams a warning in REPL when I use script editor

### ISSUE THREAD

**Issue by HenriDeh** [JunoLab/Atom.jl#224]
This warning is spammed in my REPL when I use the file editor in Atom. It is triggered by using the Enter key.
```
┌ Warning: Atom.jl: unrecognised message updateeditor.
└ @ Atom ~/.julia/packages/Atom/BVajq/src/comm.jl:171
```
It happens since the last uber-juno, julia-client update. 

Versions:
Atom.jl : 0.11.3
julia-client : 0.11.3
uber-juno : 0.3.0
Atom: 1.40.1 (latest on software manager)

**Comment by HenriDeh** [comment]
Same as https://github.com/JunoLab/Juno.jl/issues/350 but this time everything is up to date

**Comment by aviatesk** [comment]
I'm sure you're not on Atom.jl 0.11.3 on the very _running julia session_.
Restarting julia will solve this.

**Comment by HenriDeh** [comment]
You mean restart Atom ? Restarting julia had no effect, julia packages are updated without the need for a fresh session to my knowledge. Restarting Atom appears to work, I did it after the julia-client update but before the Atom.jl update. So the lesson today is to restart after both.
