### ISSUE TITLE
Add Atom installs v0.9.1

### ISSUE THREAD

**Issue by dfioravanti** [JunoLab/Atom.jl#231]
Hi all,

I just installed Juno following the instructions from the website. It complains that the version of Atom.jl is not the expected on. Via Pkg.status("Atom") I got that the installed version is v0.9.1. I removed Atom.jl via Pkg and reinstalled but it is still v0.9.1 and there is no way to upgrade to v0.11.x. 

I am using Julia 1.3. on Ubuntu 18.04. I installed Julia with the "Generic Linux Binaries for x86". 

Any idea how to fix this?

Thanks a lot for the amazing work.

**Comment by pfitzseb** [comment]
Try 
```
pkg> add Atom@0.11.3
```
That will fail, but the package manager will tell you why.

**Comment by dfioravanti** [comment]
Thanks a lot that helped. I closed it since it is not a problem with Atom in the end.

If it helps someone else, apparently LanguageServer and Atom require incompatible versions of CSTParser and that forces v0.9.1 to be installed.

**Comment by aviatesk** [comment]
most probably because of #226 if your CSTParser.jl version is higher than `v1.0.0`.
