### ISSUE TITLE
Hard to extend plotting facility

### ISSUE THREAD

**Issue by LewisHein** [JunoLab/Atom.jl#28]
The current plotting facility is hard to extend with a new plots package. It seems to require non-obvious edits to the Atom code. Instead, the package maker should just be able to define a function, say dispatom() and have their multimedia plot magically displayed in the plots pane.

At the very least there should be more documentation that explains why just editing src/display/plots.jl doesn't work and what should be done instead.

**Comment by pfitzseb** [comment]
It's not so much hard to extend plotting to other types, but rather very badly documented, I think.

If I understand this correctly, two things need to be done:
 - The display system (Media.jl) needs to know that your type is a plot. For this you should be able to just call something like `Media.media(YourPackage.YourType, Media.Graphical)` ([example](https://github.com/JunoLab/Media.jl/pull/6/files)).
 - Atom needs to know how exactly to render that type. For that you need to define a `Atom.render(PlotPane, YourPackage.YourType)` method, like  [here](https://github.com/JunoLab/Atom.jl/pull/27/files).

That said, I haven't yet tried doing the above from outside of Media.jl/Atom.jl, so not sure if it's as easy as I think.

**Comment by tbreloff** [comment]
I was working on this yesterday for Plots. Check out the dev branch.  It works for pyplot, gadfly, and gr backends. See the Juno gitter chat for progress we made towards the plotly backend.
