### ISSUE TITLE
Precompilation failure on v1.1

### ISSUE THREAD

**Issue by jebej** [JunoLab/Atom.jl#282]
Precompilation fails because of `GenericCondition`

```
[ Info: Precompiling Atom [c52e3926-4ff0-5f6e-af25-54175e0327b1]
ERROR: LoadError: UndefVarError: GenericCondition not defined
Stacktrace:
 [1] _precompile_() at C:\Users\XXXXXX\.julia\packages\Atom\ooRtV\src\precompile.jl:95
```

**Comment by jebej** [comment]
I had to remove two statements for `GenericCondition`, and one for `restart_copyto_nonleaf!`. After that it worked.

**Comment by aviatesk** [comment]
We've only tested on v1 (stable), v1.3 and v1.4.
I recommend you bump your Julia.

**Comment by jebej** [comment]
I would be preferable if things worked on Julia stable, especially since the package version hasn't been bound, and so everyone on 1.0 will get the update.

Especially since the only issue is with the precompile statements.

**Comment by jebej** [comment]
For now multithreading is more efficient on 1.1.

If removing the 3 statements is acceptable I can make a PR.

**Comment by aviatesk** [comment]
fair enough. please go for PR :)
