### ISSUE TITLE
socket `println` can get interleaved

### ISSUE THREAD

**Issue by ssfrr** [JunoLab/Atom.jl#3]
I think this is one of the root causes of junolab/atom-julia-client#19. When I added a mutex to comm.jl as in the below code I'm seeing all the incoming messages properly separated by newlines.

It's pretty ugly and really should be an outgoing message queue or something, but I think it demonstrates the issue.

```
type Mutex
    locked::Bool
    cond::Condition

    Mutex() = new(false, Condition())
end

function lock(m::Mutex)
  while m.locked
      wait(m.cond)
  end
  m.locked = true
end

function unlock(m::Mutex)
    m.locked = false
    notify(m.cond)
end

global msgMutex = Mutex()
function msg(t, data)
  isactive(sock) || return
  lock(msgMutex)
  println(sock, json(c(t, data)))
  unlock(msgMutex)
end
```

**Comment by one-more-minute** [comment]
Weirdly enough I haven't seen this at all myself, although I have noticed the `STDOUT` pipe breaking occasionally, which could potentially be related. Now I'm struggling to reproduce that – anyone else notice it?

A mutex might be more generally useful (if we decide to apply to to eval, for example), and I'm not sure a queue would be cleaner (would you have to spawn a separate task to watch the queue?) but that's really just speculation – if you're willing to throw a PR together I'm happy with whatever you think is best.

**Comment by ssfrr** [comment]
After some digging it looks like those `println` calls are *supposed* to be atomic. I think this problem is caused by JuliaLang/julia#10615. It does turn out there is a Mutex implementation exported from base. It's called ReentrantLock. For now it seems that wrapping the `println` in another lock works around the issue.
