### ISSUE TITLE
Atom is not working on Julia in openSUSE

### ISSUE THREAD

**Issue by leocastel** [JunoLab/Atom.jl#33]
I cannot solve the problem bellow that happens when a try to use the command Pkg.add("Atom").
Does any one know how to fix that?
Thanks in advance.

julia> Pkg.update()
INFO: Updating METADATA...
INFO: Computing changes...
INFO: No packages to install, update or remove

julia> Pkg.add("Atom")
INFO: Nothing to be done

julia> using Atom
INFO: Precompiling module Atom...
ERROR: LoadError: libnettle not properly installed. Please run Pkg.build("Nettle")
[inlined code] from none:2
in anonymous at no file:0
while loading /home/leo/.julia/v0.4/Nettle/src/Nettle.jl, in expression starting on line 10
ERROR: LoadError: Failed to precompile Nettle to /home/leo/.julia/lib/v0.4/Nettle.ji
in compilecache at loading.jl:400
[inlined code] from none:2
in anonymous at no file:0
while loading /home/leo/.julia/v0.4/WebSockets/src/WebSockets.jl, in expression starting on line 23
ERROR: LoadError: LoadError: Failed to precompile WebSockets to /home/leo/.julia/lib/v0.4/WebSockets.ji
in compilecache at loading.jl:400
[inlined code] from none:2
in anonymous at no file:0
while loading /home/leo/.julia/v0.4/Mux/src/websockets_integration.jl, in expression starting on line 1
while loading /home/leo/.julia/v0.4/Mux/src/Mux.jl, in expression starting on line 26
ERROR: LoadError: LoadError: Failed to precompile Mux to /home/leo/.julia/lib/v0.4/Mux.ji 
in compilecache at loading.jl:400 
[inlined code] from none:2 
in anonymous at no file:0 
while loading /home/leo/.julia/v0.4/Blink/src/content/content.jl, in expression starting on line 1 
while loading /home/leo/.julia/v0.4/Blink/src/Blink.jl, in expression starting on line 8 
ERROR: LoadError: Failed to precompile Blink to /home/leo/.julia/lib/v0.4/Blink.ji 
in compilecache at loading.jl:400 
[inlined code] from none:2 
in anonymous at no file:0 
while loading /home/leo/.julia/v0.4/Atom/src/Atom.jl, in expression starting on line 5 
ERROR: Failed to precompile Atom to /home/leo/.julia/lib/v0.4/Atom.ji 
in compilecache at loading.jl:400

julia> Pkg.build("Nettle")
INFO: Building Nettle 
===============================[ ERROR: Nettle ]================================

LoadError: could not spawn apt-cache showpkg libnettle4: no such file or directory (ENOENT) 
while loading /home/leo/.julia/v0.4/Nettle/deps/build.jl, in expression starting on line 39

================================================================================

=================================================================================================[ BUILD ERRORS ]=================================================================================================

WARNING: Nettle had build errors.

packages with build errors remain installed in /home/leo/.julia/v0.4
build the package(s) and all dependencies with Pkg.build("Nettle")
build a single package by running its deps/build.jl script

**Comment by MikeInnes** [comment]
I think your best bet would be to open an issue on the Nettle.jl repo – hopefully the maintainers will be able to help you with the build process.

**Comment by leocastel** [comment]
They really did! Problem solved

**Comment by MikeInnes** [comment]
Great!
