### ISSUE TITLE
Atom.jl for Julia 0.5

### ISSUE THREAD

**Issue by rapus95** [JunoLab/Atom.jl#35]
executing "using Atom" results in that "log":
https://gist.github.com/rapus95/46d10cc14d37932fd1d3ab4976f0d81b

The problem is somewhere in the middle (after lots of deprecated warnings) that says:
```
ERROR: LoadError: JuliaParser.Diagnostics.Diagnostic([JuliaParser.Diagnostics.Message(:error,JuliaParser.Tokens.SourceRange(0xffffffff,0x0000ffff,0xff),"invalid character \"\r\"")])
```

Thus i can't precompile Atom (and CodeTools) and thus i can't use Atom with julia 0.5

Any kind of tip or instruction what i have to change in the source files would be appreciated.

Thanks for diving/looking into it.

**Comment by pfitzseb** [comment]
You can switch to the `julia-0.5` branches of Atom and CodeTools via e.g. `Pkg.checkout("Atom", "julia-0.5")`. Should any other package fail to precompile then, try checking that out as well to get on the master branch (may be necessary for JuliaParser, but it's been a while since I last tried Atom on Julia 0.5).

**Comment by rapus95** [comment]
Did checkout JuliaParser to master and CodeTools & Atom to julia-0.5 but the error is still the same :/

**Comment by pfitzseb** [comment]
Does precompiling JuliaParser by itself work, i.e. what does `using JuliaParser` do? 
I can try getting it running again later today, but don't have the time right now.

**Comment by rapus95** [comment]
using JuliaParser
executed just fine w/o any complaints


Am 13. Mai 2016 11:20:34 vorm. schrieb Sebastian Pfitzner 
<notifications@github.com>:

**Comment by pfitzseb** [comment]
Alright, Atom.jl works on 0.5 on Windows now -- I'm pretty sure ASTInterpreter is broken on Windows right now, so I have disabled that functionality for the time being.

**Comment by ufechner7** [comment]
Can this be closed now?

**Comment by pfitzseb** [comment]
Yes.
