### ISSUE TITLE
julia-0.4: WARNING: Atom.jl: unrecognised message workspace

### ISSUE THREAD

**Issue by dlfivefifty** [JunoLab/Atom.jl#38]
I get warnings in the console

WARNING: Atom.jl: unrecognised message workspace

I'm on the julia-0.4 branch of Atom & CodeTools, and the master branch of julia-clinent & ink

**Comment by MikeInnes** [comment]
This should be fixed with https://github.com/JunoLab/Atom.jl/commit/0589f36f4d6c9d20d2c8dd924ef4280e81911114. Thanks for the report!
