### ISSUE TITLE
Juno Pkg.Update on 0.5 with Private Repository

### ISSUE THREAD

**Issue by ChrisRackauckas** [JunoLab/Atom.jl#43]
On v0.5 Julia makes you enter your credentials for your private repos when doing Pkg.update, but Juno's console doesn't allow you to enter the inputs:

![junogit](https://cloud.githubusercontent.com/assets/1814174/16027770/9006f8ec-318d-11e6-8931-c3ce992becf6.PNG)

Thus you have to do all `Pkg.update`s from the REPL.

**Comment by pfitzseb** [comment]
There's a `Send To Stdin`-command which sends the current selection to Julias STDIN -- not sure if or how well that works though.

**Comment by pfitzseb** [comment]
This should just work on latest master (where we pipe `readline(STDIN)` to `Juno.ipnut()`).
