### ISSUE TITLE
brittle interrupt handling

### ISSUE THREAD

**Issue by pfitzseb** [JunoLab/Atom.jl#45]
This is kinda strange -- on one machine (julia on commit 858371f, so after the changes to `^C` handling) interrupts kinda work (meaning: most work fine, but sometimes a `schedule: Task not runnable`-error is thrown); on other installations they don't work at all and Julia just dies.

That's all on Windows though, dunno about other OSs.

cc: @ChrisRackauckas, @MikeInnes

**Comment by ChrisRackauckas** [comment]
I won't be able to check this for a few weeks. I'll let you know then.
