### ISSUE TITLE
cannot display Dictionary

### ISSUE THREAD

**Issue by YongHee-Kim** [JunoLab/Atom.jl#52]
After updating Atom.io package ink and julia-client to 0.5.0 
Atom couldn't display Dictionary type with following error

'julia> d = Dict(1=>2)
UndefVarError: options not defined
 [inlined code] from C:\Users\Yonghee\.julia\v0.4\Atom\src\display\objects.jl:49
......`

**Systeminfo**
```
julia> versioninfo()
Julia Version 0.4.6
Commit 2e358ce (2016-06-19 17:16 UTC)
Platform Info:
  System: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by YongHee-Kim** [comment]
seems related to 8d58ffc. 

changing `object.jl line:49` to this 
`push!(st, SubTree(span(c(render(i, key), " → ")), val))`

fixed problem

**Comment by pfitzseb** [comment]
Yes, this shouldn't be an issue anymore. If it is, feel free to reopen!
