### ISSUE TITLE
Only two-dimensional images are supported

### ISSUE THREAD

**Issue by jianghaizhu** [JunoLab/Atom.jl#61]
When I am working in Juno and I am loading a 3D volume or a stack of 2D images,  I got the following error.

> Only two-dimensional images are supported
>  in assert2d at Images/src/core.jl:1147
>  in #show#135 at Images/src/writemime.jl:18
>  in verbose_show at ./multimedia.jl:50
>  in base64encode at ./multimedia.jl:76
>  in  at Atom/src/display/plots.jl:21
>  in verbose_show at ./strings/io.jl:37
>  in view at Juno/src/base/base.jl:3 [inlined]
>  in render at Atom/src/display/view.jl:20 [inlined]
>  in render at Juno/src/types.jl:18 [inlined]
>  in render at Atom/src/eval.jl:63
>  in handlemsg at Atom/src/comm.jl:148
>  in at ./event.jl:68

I understand Juno doesn't support 3D image display. But I don't want to display it. I simply want to take the image data and manipulate it and write it out.

**Comment by MikeInnes** [comment]
Looks like this is due to us trying to display the image [here](https://github.com/JunoLab/Atom.jl/blob/3834b22f7b8443a005df7763f38e6d22151b0fde/src/display/plots.jl#L9). It shouldn't be too hard to fix this to check the image is 2D and fall back to something else if not.

**Comment by pfitzseb** [comment]
This isn't relevant any more because Juno related plotting clode has been moved to the ploting packages.
