### ISSUE TITLE
Indention bug in Atom Juno with .jl files

### ISSUE THREAD

**Issue by ArchieCall** [JunoLab/Atom.jl#62]
```
#-- demonstrate indention bug in .jl files within Atom - Juno IDE
a = 1
#-- words ( for while function if begin ) in comment lines
#-- these words when not in a comment should cause indention
#-- these words in a comment line by itself do not indent (correct)
#-- these words in a comment at end of a statement cause indention (incorrect)

uu = 4
#-- the word for does not cause an indention. (correct)
y = 7
c = 3  #-- the word for causes indention. (incorrect)
  d = 4 #-- bland comment
  e = 5  #-- the word function causes indention. (incorrect)
    t = 6 #-- the word for causes indention. (incorrect)
      a1 = 7 #-- bland commnet
      a2 = 8  # word begin
        d = 4 # word if
          cowboy = 9
```

**Comment by pfitzseb** [comment]
This is strange -- I don't see any form of indentation when there's a block opener in a comment. Are your Atom packages up to date, specifically `language-julia` and `julia-client`?

**Comment by ArchieCall** [comment]
julia-client is at 0.5.6
language-julia is at 0.7.0
Both of these show as current.
What do you mean by block opener in comment?

The block below shows how the for in the comment following a = 1 indents the next line?
```
a = 1  #-- for
  b = 2
```
This also happens when you have text in the middle of a println line.
```
println("a simple line of text containing the word for")
  b = 2
```

If I capitalize the For, it does not happen?
```
println("a simple line of text containing the word For")
b = 2
```

Maybe there is some other settting an Atom package.
Go figure...Arch

**Comment by pfitzseb** [comment]
Uhoh, I see what you mean -- wasn't on the latest version of `language-julia` myself. And it's even my fault: https://github.com/JuliaEditorSupport/atom-language-julia/commit/abecd194d0994694eacce65d20beccb774cdcc52 ;)
I'll look into fixing this.

**Comment by ArchieCall** [comment]
By the way.  Atom-Juno is great for developing code.  I like the new console how you interact directly with Julia without having to go out a terminal.

**Comment by pfitzseb** [comment]
Glad you like it!

This bug should be fixed as soon as https://github.com/JuliaEditorSupport/atom-language-julia/pull/83 is merged and a new release tagged. Sorry for the annoyance...

**Comment by ArchieCall** [comment]
I installed language-julia v0.8.0 and the indention is now working properly.  Good job!
