### ISSUE TITLE
LoadError in julia0.4.6

### ISSUE THREAD

**Issue by postoroniy** [JunoLab/Atom.jl#64]
julia> Pkg.add("Atom")
INFO: Installing Atom v0.4.5
INFO: Installing Blink v0.3.5
INFO: Installing CodeTools v0.3.1
INFO: Installing Codecs v0.2.0
INFO: Installing FactCheck v0.4.3
INFO: Installing Hiccup v0.0.3
INFO: Installing HttpCommon v0.2.6
INFO: Installing HttpParser v0.2.0
INFO: Installing HttpServer v0.1.6
INFO: Installing JuliaParser v0.6.4
INFO: Installing LNR v0.0.2
INFO: Installing Lazy v0.11.3
INFO: Installing MacroTools v0.3.2
INFO: Installing MbedTLS v0.3.0
INFO: Installing Media v0.2.3
INFO: Installing Mustache v0.1.2
INFO: Installing Mux v0.2.2
INFO: Installing Requires v0.2.2
INFO: Installing WebSockets v0.2.1
INFO: Building HttpParser
INFO: Building MbedTLS
INFO: Package database updated
julia>using Atom
INFO: Precompiling module Atom...
WARNING: both Lazy and Requires export "@init"; uses of it in module Blink must be qualified
ERROR: LoadError: LoadError: LoadError: UndefVarError: @init not defined
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:320
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:320
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:320
 [inlined code] from none:2
 in anonymous at no file:0
 in process_options at ./client.jl:257
 in _start at ./client.jl:378
while loading /home/slava/.julia/v0.4/Blink/src/content/config.jl, in expression starting on line 4
while loading /home/slava/.julia/v0.4/Blink/src/content/content.jl, in expression starting on line 27
while loading /home/slava/.julia/v0.4/Blink/src/Blink.jl, in expression starting on line 9
ERROR: LoadError: Failed to precompile Blink to /home/slava/.julia/lib/v0.4/Blink.ji
 in error at ./error.jl:21
 in compilecache at loading.jl:400
 in require at ./loading.jl:240
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:320
 [inlined code] from none:2
 in anonymous at no file:0
 in process_options at ./client.jl:257
 in _start at ./client.jl:378
while loading /home/slava/.julia/v0.4/Atom/src/Atom.jl, in expression starting on line 5
ERROR: Failed to precompile Atom to /home/slava/.julia/lib/v0.4/Atom.ji
 in error at ./error.jl:21
 in compilecache at loading.jl:400
 in require at ./loading.jl:266
julia> Pkg.status()
10 required packages:
- ArrayFire                     0.0.3
- Atom                          0.4.5
- IJulia                        1.3.2
- ImageMagick                   0.1.8
- ImageView                     0.2.0
- JSON                          0.8.0
- MAT                           0.3.1
- Netpbm                        0.1.1
- TestImages                    0.1.1
- Wavelets                      0.5.2
  47 additional packages:
- BinDeps                       0.4.5
- Blink                         0.3.5
- Blosc                         0.1.7
- BufferedStreams               0.2.0
- Cairo                         0.2.35
- CodeTools                     0.3.1
- Codecs                        0.2.0
- ColorTypes                    0.2.8
- ColorVectorSpace              0.1.11
- Colors                        0.6.8
- Compat                        0.9.2
- Conda                         0.3.2
- Dates                         0.4.4
- FactCheck                     0.4.3
- FileIO                        0.1.3
- FixedPointNumbers             0.1.8
- Graphics                      0.1.3
- HDF5                          0.6.6
- Hiccup                        0.0.3
- HttpCommon                    0.2.6
- HttpParser                    0.2.0
- HttpServer                    0.1.6
- Images                        0.5.11
- IniFile                       0.2.5
- JuliaParser                   0.6.4
- LNR                           0.0.2
- Lazy                          0.11.3
- Libz                          0.2.0
- MacroTools                    0.3.2
- MbedTLS                       0.3.0
- Media                         0.2.3
- Mustache                      0.1.2
- Mux                           0.2.2
- Nettle                        0.2.4
- Reexport                      0.0.3
- Requires                      0.2.2
- SHA                           0.2.1
- SIUnits                       0.0.6
- StatsBase                     0.10.0
- TexExtensions                 0.0.3
- Tk                            0.4.0
- URIParser                     0.1.6
- WebSockets                    0.2.1
- Winston                       0.12.0
- ZMQ                           0.3.4
- ZipFile                       0.2.6
- Zlib                          0.1.12

**Comment by MikeInnes** [comment]
Is this still an error after doing `Pkg.update()`?

**Comment by postoroniy** [comment]
julia 0.4.6  can't check
julia 0.5.0 no error

**Comment by jingpengwu** [comment]
I got this in julia 0.5.0

both `Atom.jl` and `CodeTools.jl` is in `julia-0.5` branch.


```
julia> using Atom
INFO: Precompiling module Atom.
WARNING: both Requires and Lazy export "@init"; uses of it in module Atom must be qualified
ERROR: LoadError: LoadError: LoadError: UndefVarError: @init not defined
 in include_from_node1(::String) at ./loading.jl:488
 in include_from_node1(::String) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in include_from_node1(::String) at ./loading.jl:488
 in include_from_node1(::String) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in include_from_node1(::String) at ./loading.jl:488
 in include_from_node1(::String) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in macro expansion; at ./none:2 [inlined]
 in anonymous at ./<missing>:?
 in eval(::Module, ::Any) at ./boot.jl:234
 in eval(::Module, ::Any) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in process_options(::Base.JLOptions) at ./client.jl:239
 in _start() at ./client.jl:318
 in _start() at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
while loading /Users/jpwu/.julia/v0.5/Atom/src/display/plots.jl, in expression starting on line 6
while loading /Users/jpwu/.julia/v0.5/Atom/src/display/display.jl, in expression starting on line 35
while loading /Users/jpwu/.julia/v0.5/Atom/src/Atom.jl, in expression starting on line 8
ERROR: Failed to precompile Atom to /Users/jpwu/.julia/lib/v0.5/Atom.ji.
 in compilecache(::String) at ./loading.jl:593
 in require(::Symbol) at ./loading.jl:422
 in require(::Symbol) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
```

```
julia> versioninfo()
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-5650U CPU @ 2.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, broadwell)
```

**Comment by pfitzseb** [comment]
You need to either be on the tagged releases or on master -- the `julia-0.5` branches aren't maintained anymore.

**Comment by jingpengwu** [comment]
thanks, works now :)

Removing the `julia-0.5` might reduce ambiguity though.

**Comment by pfitzseb** [comment]
Done. You'll still have them locally though.
