### ISSUE TITLE
MethodError popup, when trying to access type field

### ISSUE THREAD

**Issue by YongHee-Kim** [JunoLab/Atom.jl#67]
```
type Mydata
    a::Int
end

type Mytype
    a::Mydata
    Mytype(a) = Mytype(Mydata(a))
end
x = Mytype(1)

```
then when I write `x.a.` this happens

![bugreport](https://cloud.githubusercontent.com/assets/7087745/19881600/a262a848-a04a-11e6-888d-457f0125de0c.gif)

**Comment by pfitzseb** [comment]
This should be fixed by https://github.com/JunoLab/CodeTools.jl/commit/7ff2b1e88cddf0d059f84df77115b539e0cdeeef.
