### ISSUE TITLE
EADDRINUSE error code wrong for macOS in precompile.jl 

### ISSUE THREAD

**Issue by ecuk** [JunoLab/Atom.jl#71]
In precompile.jl there is a (new) piece of code that chooses a port for the mock server. It is hard-coded to look for an EADDRINUSE error number of -4091. On macOS, and perhaps other *nix systems, the error code returned is -48, not -4091. The comparison fails and the exception is simply rethrown instead of trying the next port.

It looks as if a comparison against Base.UV_EADDRINUSE instead of a hard-coded number would fix the problem.

**Comment by pfitzseb** [comment]
Thanks for the note -- this should be fixed with https://github.com/JunoLab/Atom.jl/commit/ff7228dd1dced5890597d03dfc67430737c084a1.

New version will hopefully be out soon.
