### ISSUE TITLE
Julia-Client Internal Error | BoundsError

### ISSUE THREAD

**Issue by masiddique** [JunoLab/Atom.jl#80]
I don't understand why I'm getting the following error:

`BoundsError: attempt to access 0-element Array{Any,1} at index [1]`

I'm using Atom as client for Julia. I have recently updated Ink and Atom. But almost every time I try to write anything in the console, this error pops up (right when I start typing). I ignore i,t and keep working. But the same error keeps repeatedly popping up. It's very annoying.

All packages are up-to-date. Julia is v 0.5.1. Atom is 1.15.0

**Comment by pfitzseb** [comment]
Can you supply the complete backtrace when the error pos up again? (You should be able to copy it out of the console)

**Comment by masiddique** [comment]
Thanks for the reply. Backtrace is as shown below:

> BoundsError: attempt to access 0-element Array{Any,1} at index [1]
 in fullsignature(::Base.Docs.Binding) at summaries.jl:40
 in signature at summaries.jl:52 [inlined]
 in withmeta(::String, ::Module) at completions.jl:49
 in collect_to!(::Array{Dict{Any,Any},1}, ::Base.Generator{Array{String,1},CodeTools.##27#28{Module}}, ::Int64, ::Int64) at array.jl:340
 in collect_to_with_first!(::Array{Dict{Any,Any},1}, ::Dict{Any,Any}, ::Base.Generator{Array{String,1},CodeTools.##27#28{Module}}, ::Int64) at array.jl:327
 in collect(::Base.Generator{Array{String,1},CodeTools.##27#28{Module}}) at array.jl:308
 in withmeta(::Array{String,1}, ::Module) at completions.jl:58
 in namecompletions_(::Module, ::Bool) at completions.jl:63
 in (::CodeTools.##5#6{CodeTools.#namecompletions_,Int64,Dict{Any,Any}})(::Module, ::Vararg{Any,N}) at utils.jl:18
 in #completions#42(::Bool, ::Function, ::String, ::Module) at completions.jl:190
 in (::CodeTools.#kw##completions)(::Array{Any,1}, ::CodeTools.#completions, ::String, ::Module) at <missing>:0
 in completions(::Module) at completions.jl:195
 in (::Atom.##89#90)(::String) at completions.jl:23
 in handlemsg(::Dict{String,Any}, ::String, ::Vararg{String,N}) at comm.jl:163
 in (::Atom.##14#17)() at event.jl:68

**Comment by pfitzseb** [comment]
Alright, thanks for supplying the backtrace. Should be fixed on master now.
This was caused by us not properly handling emtpy docstrings.
