### ISSUE TITLE
Feature request: View previously exported profile data

### ISSUE THREAD

**Issue by Pbellive** [JunoLab/Atom.jl#95]
Hi folks,
               I'm loving the new profile viewing capabilities in Juno. Thanks for the great work! One feature that would be really nice to have is the ability to use `profiler()` to visualize profile data previously exported using `Profile.retrieve()`. This is supported by ProfileView.jl but it would be nice to do inside Juno. For reference here's a link to how I believe ProfileView.jl converts profiling data from `retrieve` format to tree format:
https://github.com/timholy/ProfileView.jl/blob/master/src/ProfileView.jl#L66

I'm afraid I'm not able to do this myself and submit a PR.

Thanks, Patrick

**Comment by pfitzseb** [comment]
This is implemented in the latest version.
