### ISSUE TITLE
Integration with Revise?

### ISSUE THREAD

**Issue by timholy** [JunoLab/Atom.jl#97]
Revise.jl automatically detects changes in source-code files and re-evaluates the changes in the proper module. There's [integration for the REPL and IJulia](https://github.com/timholy/Revise.jl/blob/0ab150ed5320b01851b3962e4f4c3a61b2e0b233/src/Revise.jl#L650-L656), but none yet for Juno. I browsed the Juno and Atom src dirs briefly; without really understanding what's going on, I'm guessing [this block](https://github.com/JunoLab/Atom.jl/blob/531aa39a0e568df2363a3fe9cd34a4a966dc6e84/src/eval.jl#L88-L114) handles interaction with user input. AFAICT, I would only have to duplicate that code in Revise, but add a call `revise()` before the `eval`. That's the route I took for the REPL, but this solution isn't great because if the user-input-handler evolves the replacement in Requires could become desynchronized.

IJulia has a nice mechanism for adding hooks. Does there exist, or is there interest in, such a mechanism for Juno?

**Comment by pfitzseb** [comment]
Wouldn't it make more sense to call revise when a file is actually modified instead of on user interaction? 
Adding `preeval`/`posteval` hooks probably makes sense anyways, but doesn't seem like the best way to enable good Revise support to me (compared to a `onSaveFile` hook).

**Comment by timholy** [comment]
I do it at the moment of user interaction for a simple reason: when I'm editing code, I might hit "save" on my editor halfway through defining a function. If it's missing its final `end`, then the rest of the file becomes unparseable. Revise attempts to handle such things gracefully, but at a minimum it is likely to result in a bit of unnecessary cache invalidation.

In contrast, when I execute a command at the REPL, I'm doing so because I expect that my edits are "done" and the function should work.

**Comment by pfitzseb** [comment]
Alright, makes sense.
For now you could just use something like
```julia
for x in ["eval", "evalall", "evalrepl"]
  old = Atom.handlers[x]
  Atom.handle(x) do data
    revise()
    old(data)
  end
end
```
but this would probably a bit nicer with hooks (though in principle this should scale just as well;  it's just a pretty ugly API).

**Comment by MikeInnes** [comment]
Does this have any advantages over just hitting `Cmd-Enter`?

**Comment by pfitzseb** [comment]
Functionally no, but it's a different workflow we could just as well support, no?

**Comment by timholy** [comment]
It's similar if the user knows to eval everything. But let's say the changes come from `Pkg.update()`, or that the user has done a search-replace across a whole project---in that case I think `Cmd-Enter` involves more manual effort.

**Comment by timholy** [comment]
BTW, I'm perfectly happy with https://github.com/JunoLab/Atom.jl/issues/97#issuecomment-317414929 as a solution, so I'll close this.
